language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t andrewt51/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true andrewt51/docker-react npm run test